BraTS_3D_viewer/urls.py
from django.urls import path
from . import views

app_name = 'BraTS_3D_viewer'
urlpatterns = [
    path('', views.case_list, name='case_list'),
    path('cases/', views.get_cases, name='get_cases'),
    path('cases/upload', views.upload_case, name='case_upload'),
    path('cases/delete/<int:pk>', views.delete_case, name='case_delete'),
    path('inference/<str:case_name>', views.infer, name='inference'),
    path('view/<str:case_name>', views.view3D),
    path('labels/<str:case_name>', views.get_labels, name='labels'),
]

BraTS_demo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('BraTS_3D_viewer.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BraTS_3D_viewer/models.py
from django.db import models

# Create your models here.
class MRICase(models.Model):
    case_id = models.CharField(max_length=50, unique=True)
    t1 = models.FileField(upload_to='cases')
    t1ce = models.FileField(upload_to='cases')
    t2 = models.FileField(upload_to='cases')
    flair = models.FileField(upload_to='cases')

    def __str__(self):
        return self.case_id

    def delete(self, *args, **kwargs):
        # delete the uploaded files before calling base class's delete method
        self.t1.delete()
        self.t1ce.delete()
        self.t2.delete()
        self.flair.delete()

        super().delete(*args, **kwargs)

BraTS_3D_viewer/forms.py
from django import forms
from .models import MRICase

class MRICaseForm(forms.ModelForm):
    class Meta:
        model = MRICase
        fields = ('case_id', 't1', 't1ce', 't2', 'flair')

BraTS_3D_viewer/views.py
from django.shortcuts import render, redirect
from django.core.files.storage import FileSystemStorage
from django.http import JsonResponse
from .forms import MRICaseForm
from .models import MRICase

import os
import torch
import numpy as np
import nibabel as nib
import time
import datetime
import torch.nn.functional as F
from BraTS_3D_viewer.seg_models.unet import UNet
from BraTS_3D_viewer.datasets.BRATS2018 import NormalizeBRATSVal, ToTensorVal
import plotly.plotly as py
import plotly.graph_objs as go


# Create your views here.

def case_list(request):
    # case list
    cases = MRICase.objects.all()
    # upload form
    form = MRICaseForm()

    return render(request, 'BraTS_3D_viewer/case_list.html', context={
        'cases': cases,
        'form': form
    })

def get_cases(request):
    # cases
    cases = MRICase.objects.all()
    cases = list(map(lambda c: {'case_id': c.case_id, 'id': c.id}, cases))

    return JsonResponse({'cases': cases})

def upload_case(request):
    if request.method == 'POST':
        form = MRICaseForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return JsonResponse({'status': 'Success'})
        else:
            return JsonResponse({'status': 'Failed to upload MRI scans.'})

    # for GET request        
    form = MRICaseForm()
    return render(request, 'BraTS_3D_viewer/upload.html', context={
        'form': form
    })

def delete_case(request, pk):
    if request.method == 'GET':
        case = MRICase.objects.get(pk=pk)
        case.delete()

    return redirect('BraTS_3D_viewer:case_list')



def _time_stamp() -> str:
    ts = time.time()
    time_stamp = datetime.datetime.fromtimestamp(ts).strftime('%Y-%m-%d %H:%M:%S')
    return time_stamp

def infer(request, case_name):
    print('{} starts predicting'.format(_time_stamp()))
    upload_dir = 'media/cases'
    seg_dir = 'media/seg'

    if not os.path.exists(seg_dir):
        os.makedirs(seg_dir)
    
    if os.path.exists(os.path.join(seg_dir, case_name + '.npy')):
        return JsonResponse({'status': 'already inferred'})

    model_path = '/home/martin/Documents/semantic_segmentation/UNet-ResidualBlock-Expansion_210_end_to_end_manual/UNet-ResidualBlock-Expansion-BRATS2018-End-to-End_batch6_training_epochs15_Adam_scheduler-step10-gamma1.0_lr5e-05_w_decay3e-05/trained_model.pt'
    device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
    

    t1_path = os.path.join(upload_dir, case_name + '_t1.nii.gz')
    t1ce_path = os.path.join(upload_dir, case_name + '_t1ce.nii.gz')
    t2_path = os.path.join(upload_dir, case_name + '_t2.nii.gz')
    flair_path = os.path.join(upload_dir, case_name + '_flair.nii.gz')

    t1 = nib.load(t1_path).get_data()
    t1ce = nib.load(t1ce_path).get_data()
    t2 = nib.load(t2_path).get_data()
    flair = nib.load(flair_path).get_data()
    sc = np.array([t1, t1ce, t2, flair]).transpose((3, 0, 1, 2))
    assert sc.shape == (155, 4, 240, 240)

    model = UNet(n_channels=4, n_classes=4, residual=True, expansion=2)
    model.load_state_dict(torch.load(model_path, map_location=device))
    model.to(device)
    model.eval()

    preds = np.zeros((155, 240, 240))

    for i in range(155):
        slice_i = sc[i]
        assert slice_i.shape == (4, 240, 240)

        normalize = NormalizeBRATSVal()
        totensor = ToTensorVal()

        slice_i = normalize(slice_i)
        slice_i = totensor(slice_i)

        # unsqueeze the dimension to 4, NxCxHxW
        slice_i = torch.unsqueeze(slice_i, dim=0)
        slice_i = slice_i.to(device)
        with torch.no_grad():
            output = model(slice_i)
            pred = torch.argmax(F.softmax(output, dim=1), dim=1, keepdim=True)
        
        # squeeze the dimension down to 2, HxW
        pred = torch.squeeze(pred)
        pred = pred.cpu().numpy()
        preds[i] = pred
    
    print('{} finishes predicting'.format(_time_stamp()))
    print(np.unique(preds), preds.shape)
    
    np.save(os.path.join(seg_dir, case_name), preds)
    
    preds = np.unique(preds).tolist()
    # release GPU memory
    del model
    del slice_i
    del pred
    del output
    
    torch.cuda.empty_cache()

    return JsonResponse({'labels': preds})


def view3D(request, case_name):
    seg_dir = 'media/seg'
    try:
        preds = np.load(os.path.join(seg_dir, case_name + '.npy'))
        assert preds.shape == (155, 240, 240)

        print('{} start preparing'.format(_time_stamp()))
        et_indices = np.argwhere(preds == 3.)
        et_xs = [ind[0] for ind in et_indices]
        et_ys = [ind[1] for ind in et_indices]
        et_zs = [ind[2] for ind in et_indices]

        edema_indices = np.argwhere(preds == 2.)
        edema_xs = [ind[0] for ind in edema_indices]
        edema_ys = [ind[1] for ind in edema_indices]
        edema_zs = [ind[2] for ind in edema_indices]

        necrotic_indices = np.argwhere(preds == 1.)
        necrotic_xs = [ind[0] for ind in necrotic_indices]
        necrotic_ys = [ind[1] for ind in necrotic_indices]
        necrotic_zs = [ind[2] for ind in necrotic_indices]

        seg_xs = et_xs + edema_xs + necrotic_xs
        seg_ys = et_ys + edema_ys + necrotic_ys
        seg_zs = et_zs + edema_zs + necrotic_zs
        seg_color = [3] * len(et_xs) + [2] * len(edema_xs) + [1] * len(necrotic_xs)
        print('{} finish preparing'.format(_time_stamp()))

        trace_seg = go.Scatter3d(
            x=seg_xs,
            y=seg_ys,
            z=seg_zs,
            mode='markers',
            marker={
                'size': 3,
                'color': seg_color,
                'colorscale': 'Viridis',
                'opacity': 0.8
            }
        )

        layout = go.Layout(
            margin=dict(
                l=0,
                r=0,
                b=0,
                t=0
            )
        )

        data_seg = [trace_seg]
        fig_seg = go.Figure(data=data_seg, layout=layout)
        py.iplot(fig_seg, filename='3D-Glioma-segmentation')
        print('{} finish plotting'.format(_time_stamp()))

        return JsonResponse({'status': 'normal'})
    except:
        return JsonResponse({'status': 'internal_error'})


def get_labels(request, case_name):
    seg_dir = 'media/seg'
    try:
        preds = np.load(os.path.join(seg_dir, case_name + '.npy'))
        assert preds.shape == (155, 240, 240)

        print('{} start preparing'.format(_time_stamp()))
        et_indices = np.argwhere(preds == 3.)
        et_xs = [int(ind[0]) for ind in et_indices]
        et_ys = [int(ind[1]) for ind in et_indices]
        et_zs = [int(ind[2]) for ind in et_indices]

        edema_indices = np.argwhere(preds == 2.)
        edema_xs = [int(ind[0]) for ind in edema_indices]
        edema_ys = [int(ind[1]) for ind in edema_indices]
        edema_zs = [int(ind[2]) for ind in edema_indices]

        necrotic_indices = np.argwhere(preds == 1.)
        necrotic_xs = [int(ind[0]) for ind in necrotic_indices]
        necrotic_ys = [int(ind[1]) for ind in necrotic_indices]
        necrotic_zs = [int(ind[2]) for ind in necrotic_indices]

        return JsonResponse({
            'et_xs': et_xs,
            'et_ys': et_ys,
            'et_zs': et_zs,
            'edema_xs': edema_xs,
            'edema_ys': edema_ys,
            'edema_zs': edema_zs,
            'necrotic_xs': necrotic_xs,
            'necrotic_ys': necrotic_ys,
            'necrotic_zs': necrotic_zs,
            'et_length': len(et_xs),
            'edema_length': len(edema_xs),
            'necrotic_length': len(necrotic_xs) 
        })
    except:
        return JsonResponse({'status': 'internal_error'})

BraTS_3D_viewer/templates/BraTS_3D_viewer/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- static CSS -->
    <link rel="stylesheet" href="{% static 'BraTS_3D_viewer/css/styles.css' %}">
    {% block css_link %}
    
    {% endblock %}

    <title>Glioma Segmentation</title>
  </head>
  <body>

    {% block header %}

    {% endblock %}
    
    {% block content %}

    {% endblock %}

    <div class="container-fluid bg-dark text-center mt-3 py-3" id="page-footer">
      <h3 class="font-weight-lighter text-light">Contact Yilin?</h3>
      <h2 class="font-weight-bold text-light">Your feedback is appreciated.</h2>
      <div class="py-2">
        <hr style="border-top-color: rgba(255, 255, 255, 0.4);">
      </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block js_scripts %}
    
    {% endblock %}
  </body>
</html>

BraTS_3D_viewer/templates/BraTS_3D_viewer/case_list.html
{% extends 'BraTS_3D_viewer/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block css_link %}
    <link rel="stylesheet" href="{% static 'BraTS_3D_viewer/css/case_list.css' %}">
{% endblock %}


{% block header %}
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="https://github.com/MartinMa28">Yilin Ma Github profile</a>
            <button id="toggler-collapse-btn" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto" id="BraTS-navbar">
                    <li class="nav-item">
                        <a class="nav-link" href="https://github.com/MartinMa28/brain-tumor-segmentation">Github Repo</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="https://www.cbica.upenn.edu/BraTS18/lboardValidation.html">BraTS leaderboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="http://10.253.218.12:8888/notebooks/BraTS_visualization.ipynb">Notebook</a>
                    </li>
                </ul>
                <button type="button" id="MRI-btn" class="btn btn-outline-primary" data-toggle="modal" data-target="#upload-MRI-modal">New MRI</button>
            </div>
        </nav>
    </header>
{% endblock %}


{% block content %}
    <style type="text/css">
        .jumbotron{
            margin-top: 0px;
            background-image: url("{% static 'BraTS_3D_viewer/imgs/brain_background.jpg' %}");
            background-size: cover;
            height: 800px;
        }
    </style>
    <div class="jumbotron jumbotron-fluid"></div>

    <!-- modal -->
    <div class="modal fade" id="upload-MRI-modal" role="dialog" tabindex="-1" aria-labelledby="upload-MRI-modal-title" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="upload-MRI-modal-title">Upload MRI</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'BraTS_3D_viewer:case_upload' %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                    </form>
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                </div>
                
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" id="modal-upload-btn">Upload</button>
                </div>
            </div>
        </div>
    </div>
    <!-- modal -->
    
    <div class="container bg-white shadow rounded" id="BraTS-container">
        <div class="row justify-content-start">
            <div class="col-sm-6 my-2" id="case_list_container">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Case ID</th>
                            <th>Operations</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for c in cases %}
                        <tr>
                            <td>{{ c.case_id }}</td>
                            <td>
                                <div class="btn-group" role="group" aria-label="operations-group">
                                    <button class="btn btn-light btn-sm inference" data-case-name="{{ c.case_id }}" data-id="{{ c.id }}">
                                        Predict
                                        <span class="spinner-border spinner-border-sm" role="status" style="visibility: hidden;" id="{{ c.id }}-inference-spinner"></span>
                                    </button>
                                    <button class="btn btn-light btn-sm view3D" data-case-name="{{ c.case_id }}" data-id="{{ c.id }}">
                                        View
                                        <span class="spinner-border spinner-border-sm" role="status" style="visibility: hidden;" id="{{ c.id }}-view-spinner"></span>
                                    </button>
                                    <button class="btn btn-light btn-sm delete_case" data-case-name="{{ c.case_id }}" data-id="{{ c.id }}">
                                        Delete
                                        <span class="spinner-border spinner-border-sm" role="status" style="visibility: hidden;" id="{{ c.id }}-delete-spinner"></span>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-sm-5 my-2" id="viewer_container"></div>
        </div>
    </div>
{% endblock %}


{% block js_scripts %}
    <script>
        const HOSTNAME_URL = "{{ request.get_host }}";
        const RESTfulAPI_URLS = {
            delete_case: "{% url 'BraTS_3D_viewer:case_delete' 999 %}",
            inference: "{% url 'BraTS_3D_viewer:inference' 999 %}",
            labels: "{% url 'BraTS_3D_viewer:labels' 999 %}",
            get_cases: "{% url 'BraTS_3D_viewer:get_cases' %}"
        };
    </script>
    <script src="{% static 'BraTS_3D_viewer/js/plotly-latest.min.js' %}"></script>
    <script src="{% static 'BraTS_3D_viewer/js/scripts.js' %}"></script>
{% endblock %}

BraTS_3D_viewer/templates/BraTS_3D_viewer/upload.html
{% extends 'BraTS_3D_viewer/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h2>Upload MRI cases</h2>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Upload</button>
    </form>
{% endblock %}